AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ManageEIPs-1region_SAM

Parameters:
  ProjectTag:
    Type: String
    Default: ManageEIPs
  EnvironmentTag:
    Type: String
    Default: dev
  OwnerTag:
    Type: String
    Default: Malik
  ManagedByTag:
    Type: String
    Default: SAM
  CostCenterTag:
    Type: String
    Default: Portfolio
  ScheduleExpressionMonthly:
    Type: String
    Default: cron(0 21 30 * ? *) # 18:00 UTC on the 30th

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 128
    Tracing: Active
    Tags:
      Project: !Ref ProjectTag
      Environment: !Ref EnvironmentTag
      Owner: !Ref OwnerTag
      ManagedBy: !Ref ManagedByTag
      CostCenter: !Ref CostCenterTag

Resources:
  ManageEIPsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-LambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-ManageEIPsPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: EC2DescribeRead
                Effect: Allow
                Action:
                  - ec2:DescribeAddresses
                  - ec2:DescribeInstances
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeTags
                Resource: "*"
              - Sid: EC2Tagging
                Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: "*"
              - Sid: EC2ReleaseEIP
                Effect: Allow
                Action:
                  - ec2:ReleaseAddress
                  - ec2:DisassociateAddress
                Resource: "*"
              - Sid: CloudWatchPutMetricData
                Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: "*"
                Condition:
                  StringEquals:
                    "cloudwatch:namespace": "ManageEIPs"
      Tags:
        - Key: Name
          Value: Role_ManageEIPsLambda
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Component
          Value: IAMRole
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: CostCenter
          Value: !Ref CostCenterTag

  ManageEIPsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-Lambda"
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt ManageEIPsLambdaRole.Arn
      AutoPublishAlias: live
      Tags:
        Name: Lambda_ManageEIPs
        Component: Lambda

  ManageEIPsScheduleMonthly:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AWS::StackName}-ScheduleMonthly"
      Description: Monthly schedule for ManageEIPs Lambda
      ScheduleExpression: !Ref ScheduleExpressionMonthly
      State: ENABLED
      Targets:
        - Arn: !GetAtt ManageEIPsFunction.Arn
          Id: LambdaTarget
      Tags:
        - Key: Name
          Value: Rule_ManageEIPsScheduleMonthly
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Component
          Value: EventBridge
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: CostCenter
          Value: !Ref CostCenterTag

  ManageEIPsAllowEventBridgeInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ManageEIPsFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ManageEIPsScheduleMonthly.Arn

  ManageEIPsAlarmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-Alarms"
      Tags:
        - Key: Name
          Value: SNS_ManageEIPsAlarms
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Component
          Value: SNS
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: CostCenter
          Value: !Ref CostCenterTag

  ManageEIPsDurationHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-DurationHigh"
      AlarmDescription: P95 duration too high
      Namespace: AWS/Lambda
      MetricName: Duration
      Dimensions:
        - Name: FunctionName
          Value: !Ref ManageEIPsFunction
      ExtendedStatistic: p95
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 3000
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ManageEIPsAlarmsTopic

      Tags:
        - Key: Name
          Value: Alarm_ManageEIPsDurationHigh
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Component
          Value: Monitoring
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: CostCenter
          Value: !Ref CostCenterTag
  ManageEIPsErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-Errors"
      AlarmDescription: Lambda errors > 0
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref ManageEIPsFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ManageEIPsAlarmsTopic

      Tags:
        - Key: Name
          Value: Alarm_ManageEIPsErrors
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Component
          Value: Monitoring
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: CostCenter
          Value: !Ref CostCenterTag
  ManageEIPsThrottlesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-Throttles"
      AlarmDescription: Lambda throttles > 0
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref ManageEIPsFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ManageEIPsAlarmsTopic

      Tags:
        - Key: Name
          Value: Alarm_ManageEIPsThrottles
        - Key: Project
          Value: !Ref ProjectTag
        - Key: Component
          Value: Monitoring
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Owner
          Value: !Ref OwnerTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: CostCenter
          Value: !Ref CostCenterTag
  ManageEIPsDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${AWS::StackName}-Dashboard"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 24,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Duration", "FunctionName", "${ManageEIPsFunction}", { "stat": "p95" } ],
                  [ ".", "Errors", ".", ".", { "stat": "Sum" } ],
                  [ ".", "Throttles", ".", ".", { "stat": "Sum" } ]
                ],
                "period": 60,
                "region": "${AWS::Region}",
                "title": "ManageEIPs - Lambda (p95 Duration / Errors / Throttles)"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 24,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "ManageEIPs", "ReleasedEIPs", "FunctionName", "${ManageEIPsFunction}", { "stat": "Sum" } ]
                ],
                "period": 300,
                "region": "${AWS::Region}",
                "title": "ManageEIPs - ReleasedEIPs (custom metric)"
              }
            }
          ]
        }

Outputs:
  LambdaFunctionName:
    Value: !Ref ManageEIPsFunction
  LambdaRoleName:
    Value: !Ref ManageEIPsLambdaRole
  ScheduleRuleName:
    Value: !Ref ManageEIPsScheduleMonthly
  AlarmsTopicArn:
    Value: !Ref ManageEIPsAlarmsTopic
  DashboardName:
    Value: !Ref ManageEIPsDashboard
